# Generated by Django 3.1.7 on 2021-03-15 22:00

import App_Blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_image', models.ImageField(blank=True, upload_to=App_Blog.models.upload_image)),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('blog_posted', models.DateTimeField(auto_now_add=True)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Login.teacher')),
            ],
            options={
                'verbose_name_plural': 'Article',
                'db_table': 'Article',
                'ordering': ('-blog_posted',),
            },
        ),
    ]
