# Generated by Django 3.1.7 on 2021-03-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Work2', '0003_auto_20210314_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=150),
        ),
    ]
