# Generated by Django 3.1.7 on 2021-03-15 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App_Work2', '0005_answer_answered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 15, 7, 41, 29, 783868, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
