# Generated by Django 3.1.7 on 2021-03-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Work2', '0007_gradedquiz_quiz_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
