# Generated by Django 3.1.7 on 2021-03-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Work2', '0008_answer_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedquiz',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
