# Generated by Django 3.1.7 on 2021-03-19 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Work2', '0009_gradedquiz_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedquiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_graded_quiz', to='App_Work2.quiz'),
        ),
    ]
