# Generated by Django 3.1.7 on 2021-03-19 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
        ('App_Work2', '0011_auto_20210319_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquiz',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentquiz',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_quiz', to='App_Login.student'),
        ),
    ]
