# Generated by Django 3.1.7 on 2021-03-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
        ('App_Work2', '0014_auto_20210319_0312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentquiz',
            unique_together={('quiz', 'taker')},
        ),
    ]
